### ISSUE TITLE
Progurd error max code52.0

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-google-play-services-ads#3]
```
[2017-06-22 14:22:44 - demo] Proguard returned with error code 1. See console
[2017-06-22 14:22:44 - demo] java.io.IOException: Can't read [E:\android-sdk-windows-orijnal\android-sdk-windows\platforms\android-25\android.jar] (Can't process class [java/text/CollationElementIterator.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))
[2017-06-22 14:22:44 - demo] 	at proguard.InputReader.readInput(InputReader.java:230)
[2017-06-22 14:22:44 - demo] 	at proguard.InputReader.readInput(InputReader.java:200)
[2017-06-22 14:22:44 - demo] 	at proguard.InputReader.readInput(InputReader.java:178)
[2017-06-22 14:22:44 - demo] 	at proguard.InputReader.execute(InputReader.java:100)
[2017-06-22 14:22:44 - demo] 	at proguard.ProGuard.readInput(ProGuard.java:196)
[2017-06-22 14:22:44 - demo] 	at proguard.ProGuard.execute(ProGuard.java:78)
[2017-06-22 14:22:44 - demo] 	at proguard.ProGuard.main(ProGuard.java:492)
[2017-06-22 14:22:44 - demo] Caused by: java.io.IOException: Can't process class [java/text/CollationElementIterator.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7))
[2017-06-22 14:22:44 - demo] 	at proguard.io.ClassReader.read(ClassReader.java:112)
[2017-06-22 14:22:44 - demo] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[2017-06-22 14:22:44 - demo] 	at proguard.io.JarReader.read(JarReader.java:65)
[2017-06-22 14:22:44 - demo] 	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[2017-06-22 14:22:44 - demo] 	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[2017-06-22 14:22:44 - demo] 	at proguard.InputReader.readInput(InputReader.java:226)
[2017-06-22 14:22:44 - demo] 	... 6 more
[2017-06-22 14:22:44 - demo] Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [52.0] (maximum 51.0, Java 1.7)
[2017-06-22 14:22:44 - demo] 	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:140)
[2017-06-22 14:22:44 - demo] 	at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
[2017-06-22 14:22:44 - demo] 	at proguard.classfile.LibraryClass.accept(LibraryClass.java:301)
[2017-06-22 14:22:44 - demo] 	at proguard.io.ClassReader.read(ClassReader.java:86)
```

**Comment by dandar3** [comment]
I think you need to change the Java compiler level on your app from 1.8 (52.0) to 1.7 at most, just like the message says.

> Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [52.0] (maximum 51.0, Java 1.7)

Select your app project > right click > `Properties` > `Java Compiler` > `Enable project specific setttings` (check) and set `Compiler compliance level` to 1.6 or 1.7

I believe `android-google-play-services-ads` (and the other projects) are set to Java 1.6 compliance.

**Comment by dandar3** [comment]
Sorry, I must be tired, your Proguard was complaining about the code in `android-sdk-windows\platforms\android-25\android.jar` being compiled with Java 1.8, it's not about your project. 

I was able to replicate it myself. Apparently according to this you need a newer Proguard.
https://stackoverflow.com/a/39514706/308836

1. Backup your existing `ANDROID_SDK\tools\proguard` (check its version first by running `java -jar ANDROID_SDK\tools\proguard\lib\proguard.jar`, it might be 4.7)
2. Download the latest version from SourceForge (e.g version 5.3)
https://sourceforge.net/projects/proguard/files/proguard/
3. Extract files from archive into `ANDROID_SDK\tools\proguard\` (run `java -jar ANDROID_SDK\tools\proguard\lib\proguard.jar` again to confirm new version)

**Comment by dandar3** [comment]
Closing, no response since last comment.

**Comment by vijaybhairavjibhaiaslaliya** [comment]
sorry for late replay,but i create your lib with progurd
thanks for your support

**Comment by dandar3** [comment]
No worries, thank you for your feedback!
